### ISSUE TITLE
SeamlessRDP broken on Windows 2012 and 2012r2

### ISSUE THREAD

**Issue by hean01-cendio** [rdesktop/seamlessrdp#1]
Needs to investigate this issue. It seems to be a problem that the window hooks dont work as expected.
##

**Comment by hean01-cendio** [comment]
Seamlessrdp tries to open same channel using WTSVirtualChannelOpen() which is not supported. I did work up to 2012 which introduced changes that prevents opening the same channel several times. It's not even supported from different processes.

Possible solution is to create a shared memory IPC from the hooks to seamlessrdpshell for read/write data over a single virtual channel.

See Kevin's second answer on this thread:

https://social.technet.microsoft.com/Forums/en-US/7ce64172-fa7a-4a70-8635-4b83a0d88a79/wtsvirtualchannelopen-fails-on-windows-server-2012-identical-code-works-fine-on-windows-server-2008

**Comment by derfian** [comment]
SeamlessRDP looks like it's working on Windows 2012 R2. Was this issue fixed through PR #2?

**Comment by hean01-cendio** [comment]
Yes, it was solved with that PR.
